import os
import sys
from typing import Tuple

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
sys.stdout.reconfigure(encoding="utf-8")

from tester import TaskConfig, TestCase, exact_match, run_module

_BASE_DIR = os.path.dirname(__file__)


def _yes_no(output: str, expected: str) -> Tuple[bool, str]:
    if output.strip().upper() == expected.upper():
        return True, ""
    return False, f"Ожидалось «{expected}», получено «{output}»"


TASKS = [
    TaskConfig(
        task_id="31",
        name="Шахматная ладья",
        filename="Задание 31.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=_yes_no,
        test_cases=[
            TestCase("4\n4\n5\n5", "NO"),
            TestCase("4\n4\n5\n4", "YES"),
            TestCase("4\n4\n4\n7", "YES"),
            TestCase("1\n1\n8\n1", "YES"),
            TestCase("1\n1\n1\n8", "YES"),
            TestCase("3\n5\n7\n2", "NO"),
            TestCase("8\n8\n1\n1", "NO"),
            TestCase("5\n1\n5\n8", "YES"),
            TestCase("1\n3\n8\n3", "YES"),
            TestCase("6\n2\n3\n5", "NO"),
        ],
    ),
    TaskConfig(
        task_id="32",
        name="Шахматный король",
        filename="Задание 32.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=_yes_no,
        test_cases=[
            TestCase("4\n4\n5\n5", "YES"),
            TestCase("1\n1\n3\n3", "NO"),
            TestCase("4\n4\n5\n4", "YES"),
            TestCase("4\n4\n4\n5", "YES"),
            TestCase("4\n4\n6\n4", "NO"),
            TestCase("1\n1\n2\n2", "YES"),
            TestCase("1\n1\n2\n1", "YES"),
            TestCase("8\n8\n7\n7", "YES"),
            TestCase("8\n8\n6\n6", "NO"),
            TestCase("1\n1\n1\n3", "NO"),
            TestCase("3\n5\n4\n6", "YES"),
            TestCase("3\n5\n2\n4", "YES"),
            TestCase("3\n5\n5\n5", "NO"),
        ],
    ),
    TaskConfig(
        task_id="33",
        name="Шахматный слон",
        filename="Задание 33.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=_yes_no,
        test_cases=[
            TestCase("4\n4\n5\n5", "YES"),
            TestCase("4\n4\n5\n4", "NO"),
            TestCase("4\n4\n4\n7", "NO"),
            TestCase("1\n1\n8\n8", "YES"),
            TestCase("1\n8\n8\n1", "YES"),
            TestCase("4\n4\n6\n6", "YES"),
            TestCase("4\n4\n6\n5", "NO"),
            TestCase("1\n1\n2\n3", "NO"),
            TestCase("3\n1\n1\n3", "YES"),
            TestCase("8\n1\n1\n8", "YES"),
            TestCase("5\n3\n3\n1", "YES"),
            TestCase("2\n2\n5\n6", "NO"),
        ],
    ),
    TaskConfig(
        task_id="34",
        name="Шахматный ферзь",
        filename="Задание 34.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=_yes_no,
        test_cases=[
            TestCase("1\n1\n2\n2", "YES"),
            TestCase("1\n1\n2\n3", "NO"),
            TestCase("1\n1\n1\n8", "YES"),
            TestCase("1\n1\n8\n1", "YES"),
            TestCase("4\n4\n7\n7", "YES"),
            TestCase("4\n4\n7\n5", "NO"),
            TestCase("8\n8\n1\n1", "YES"),
            TestCase("1\n5\n8\n5", "YES"),
            TestCase("3\n1\n3\n8", "YES"),
            TestCase("2\n3\n5\n6", "YES"),
            TestCase("1\n2\n3\n4", "YES"),
            TestCase("1\n1\n3\n4", "NO"),
        ],
    ),
    TaskConfig(
        task_id="35",
        name="Шахматный конь",
        filename="Задание 35.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=_yes_no,
        test_cases=[
            TestCase("1\n1\n1\n4", "NO"),
            TestCase("2\n4\n3\n2", "YES"),
            TestCase("1\n1\n2\n3", "YES"),
            TestCase("1\n1\n3\n2", "YES"),
            TestCase("1\n1\n2\n2", "NO"),
            TestCase("1\n1\n3\n3", "NO"),
            TestCase("4\n4\n6\n5", "YES"),
            TestCase("4\n4\n5\n6", "YES"),
            TestCase("4\n4\n2\n3", "YES"),
            TestCase("4\n4\n3\n6", "YES"),
            TestCase("1\n1\n3\n4", "NO"),
            TestCase("8\n8\n6\n7", "YES"),
            TestCase("8\n1\n6\n2", "YES"),
            TestCase("1\n1\n4\n2", "NO"),
            TestCase("5\n5\n7\n6", "YES"),
            TestCase("5\n5\n3\n6", "YES"),
            TestCase("5\n5\n7\n4", "YES"),
            TestCase("5\n5\n3\n4", "YES"),
            TestCase("5\n5\n6\n7", "YES"),
            TestCase("5\n5\n4\n7", "YES"),
            TestCase("5\n5\n6\n3", "YES"),
            TestCase("5\n5\n4\n3", "YES"),
        ],
    ),
    TaskConfig(
        task_id="36",
        name="Тип треугольника",
        filename="Задание 36.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=exact_match,
        test_cases=[
            TestCase("3\n4\n5",   "Прямоугольный"),
            TestCase("1\n2\n3",   "Не существует"),
            TestCase("1\n1\n1",   "Остроугольный"),
            TestCase("3\n4\n6",   "Тупоугольный"),
            TestCase("5\n6\n7",   "Остроугольный"),
            TestCase("5\n12\n13", "Прямоугольный"),
            TestCase("8\n15\n17", "Прямоугольный"),
            TestCase("1\n1\n2",   "Не существует"),
            TestCase("2\n2\n3",   "Тупоугольный"),
            TestCase("10\n10\n1", "Остроугольный"),
            TestCase("1\n10\n10", "Остроугольный"),
            TestCase("7\n24\n25", "Прямоугольный"),
            TestCase("2\n3\n4",   "Тупоугольный"),
            TestCase("5\n5\n6",   "Остроугольный"),
            TestCase("5\n5\n8",   "Тупоугольный"),
            TestCase("1\n2\n4",   "Не существует"),
            TestCase("3\n3\n3",   "Остроугольный"),
        ],
    ),
    TaskConfig(
        task_id="37",
        name="Грибы",
        filename="Задание 37.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=exact_match,
        test_cases=[
            TestCase("1",    "гриб"),
            TestCase("2",    "гриба"),
            TestCase("3",    "гриба"),
            TestCase("4",    "гриба"),
            TestCase("5",    "грибов"),
            TestCase("11",   "грибов"),
            TestCase("12",   "грибов"),
            TestCase("13",   "грибов"),
            TestCase("14",   "грибов"),
            TestCase("21",   "гриб"),
            TestCase("22",   "гриба"),
            TestCase("24",   "гриба"),
            TestCase("100",  "грибов"),
            TestCase("101",  "гриб"),
            TestCase("111",  "грибов"),
            TestCase("112",  "грибов"),
            TestCase("114",  "грибов"),
            TestCase("121",  "гриб"),
            TestCase("1000", "грибов"),
            TestCase("1001", "гриб"),
            TestCase("1011", "грибов"),
        ],
    ),
    TaskConfig(
        task_id="38",
        name="Упорядочить три числа",
        filename="Задание 38.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=["For", "While", "FunctionDef"],
        max_constructs={"If": 3},
        check_pep8=True,
        validator=exact_match,
        test_cases=[
            TestCase("1\n2\n1",   "1 1 2"),
            TestCase("3\n1\n2",   "1 2 3"),
            TestCase("3\n2\n1",   "1 2 3"),
            TestCase("1\n1\n1",   "1 1 1"),
            TestCase("2\n1\n1",   "1 1 2"),
            TestCase("1\n2\n2",   "1 2 2"),
            TestCase("1\n1\n2",   "1 1 2"),
            TestCase("5\n3\n4",   "3 4 5"),
            TestCase("-1\n0\n-2", "-2 -1 0"),
            TestCase("10\n10\n5", "5 10 10"),
            TestCase("0\n0\n0",   "0 0 0"),
            TestCase("100\n1\n50", "1 50 100"),
        ],
    ),
    TaskConfig(
        task_id="39",
        name="Високосный год",
        filename="Задание 39.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=_yes_no,
        test_cases=[
            TestCase("2024", "YES"),
            TestCase("1900", "NO"),
            TestCase("2000", "YES"),
            TestCase("2100", "NO"),
            TestCase("2200", "NO"),
            TestCase("2400", "YES"),
            TestCase("1600", "YES"),
            TestCase("1700", "NO"),
            TestCase("2023", "NO"),
            TestCase("2001", "NO"),
            TestCase("4",    "YES"),
            TestCase("1",    "NO"),
            TestCase("100",  "NO"),
            TestCase("400",  "YES"),
            TestCase("800",  "YES"),
            TestCase("1800", "NO"),
        ],
    ),
    TaskConfig(
        task_id="310",
        name="Котлеты",
        filename="Задание 310.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=exact_match,
        test_cases=[
            TestCase("3\n5\n2",  "10"),
            TestCase("2\n5\n3",  "15"),
            TestCase("5\n3\n11", "15"),
            TestCase("5\n3\n5",  "6"),
            TestCase("10\n5\n1", "10"),
            TestCase("10\n5\n3", "10"),
            TestCase("1\n3\n1",  "6"),
            TestCase("1\n5\n3",  "30"),
            TestCase("1\n1\n5",  "10"),
            TestCase("2\n3\n2",  "6"),
            TestCase("2\n3\n4",  "12"),
            TestCase("2\n3\n5",  "15"),
            TestCase("3\n2\n4",  "6"),
            TestCase("4\n5\n5",  "15"),
            TestCase("3\n1\n6",  "4"),
            TestCase("4\n5\n7",  "20"),
            TestCase("6\n4\n9",  "12"),
        ],
    ),
    TaskConfig(
        task_id="311",
        name="Число прописью",
        filename="Задание 311.py",
        time_limit=5.0,
        memory_limit_bytes=64 * 1024 * 1024,
        forbidden_constructs=[],
        check_pep8=True,
        validator=exact_match,
        test_cases=[
            TestCase("100", "сто"),
            TestCase("200", "двести"),
            TestCase("300", "триста"),
            TestCase("400", "четыреста"),
            TestCase("500", "пятьсот"),
            TestCase("600", "шестьсот"),
            TestCase("700", "семьсот"),
            TestCase("800", "восемьсот"),
            TestCase("900", "девятьсот"),
            TestCase("110", "сто десять"),
            TestCase("120", "сто двадцать"),
            TestCase("130", "сто тридцать"),
            TestCase("140", "сто сорок"),
            TestCase("150", "сто пятьдесят"),
            TestCase("160", "сто шестьдесят"),
            TestCase("170", "сто семьдесят"),
            TestCase("180", "сто восемьдесят"),
            TestCase("190", "сто девяносто"),
            TestCase("111", "сто одиннадцать"),
            TestCase("112", "сто двенадцать"),
            TestCase("113", "сто тринадцать"),
            TestCase("114", "сто четырнадцать"),
            TestCase("115", "сто пятнадцать"),
            TestCase("116", "сто шестнадцать"),
            TestCase("117", "сто семнадцать"),
            TestCase("118", "сто восемнадцать"),
            TestCase("119", "сто девятнадцать"),
            TestCase("101", "сто один"),
            TestCase("102", "сто два"),
            TestCase("103", "сто три"),
            TestCase("104", "сто четыре"),
            TestCase("105", "сто пять"),
            TestCase("106", "сто шесть"),
            TestCase("107", "сто семь"),
            TestCase("108", "сто восемь"),
            TestCase("109", "сто девять"),
            TestCase("256", "двести пятьдесят шесть"),
            TestCase("814", "восемьсот четырнадцать"),
            TestCase("999", "девятьсот девяносто девять"),
            TestCase("531", "пятьсот тридцать один"),
            TestCase("782", "семьсот восемьдесят два"),
            TestCase("430", "четыреста тридцать"),
            TestCase("601", "шестьсот один"),
            TestCase("350", "триста пятьдесят"),
            TestCase("921", "девятьсот двадцать один"),
        ],
    ),
]

if __name__ == "__main__":
    result = run_module("Условные конструкции", TASKS, _BASE_DIR)
    sys.exit(0 if result.solved_tasks == result.total_tasks else 1)
